### ISSUE TITLE
benchit doesn't work with the latest matplotlib (3.11.0)

### ISSUE THREAD

**Issue by itamarst** [droyed/benchit#8]
Using the example in the README:

```
Traceback (most recent call last):                                             
  File "/tmp/go.py", line 9, in <module>                                       
    t.plot(logy=True, logx=True)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.14/site-packages/benchit/main.py", line 1147, in plot
    fullscreenfig(ax, pause_timefs, print_info=debug_plotfs)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.14/site-packages/benchit/main.py", line 84, in fullscreenfig
    if backend in matplotlib.rcsetup.non_interactive_bk:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.rcsetup' has no attribute 'non_interactive_bk'
```

Works with versions before 3.11, so it's a recent change.

Thank you for creating this library! Using it to generate a graph for one of the chapters of my book, https://pythonspeed.com/products/practicesperformance/
